spring.datasource.url=jdbc:PostgreSQL://localhost:3306/autorecibo?useSSL=false&serverTimezone=UTC
spring.datasource.username=autorecibo
spring.datasource.password=autorecibo

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false
jwt.secret=qKJmoBr36FiYRE3U7EV/2OmEx3QgEMd1BJsSiM4cHPc=